version: "3.5"

services:

  mysql:
    image: mysql:8
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      TZ: Europe/Moscow
    volumes:
      - ./mysql:/etc/mysql/conf.d
      - ./source06:/docker-entrypoint-initdb.d