version: "3.5"

services:

  mysql:
    image: mysql:8
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: mypass
      TZ: Europe/Moscow
    volumes:
      - ./_vk_db_seed.sql:/docker-entrypoint-initdb.d/_init1.sql
